namespace IsoEnums.Generator;

using System.Globalization;
using System.Text;
using System.Xml;
using Neco.Common.Extensions;

internal static class BaseGenerator {
	
	public static IFormatProvider NumberFormatForEnums { get; } = new NumberFormatInfo { NumberGroupSeparator = "_" };
	
	public static void AppendDefaultHeader(StringBuilder sb) {
		sb.AppendLine("// <auto-generated>");
		sb.AppendLine("//   This file was generated by a tool; you should avoid making direct changes.");
		sb.AppendLine("// </auto-generated>");
		sb.AppendLine(CultureInfo.InvariantCulture, $"// Generated on {DateTime.UtcNow:F} UTC");
		sb.AppendLine();
	}
	
	public static String CalculateFrom3And2Code(String code3, String? code2) {
		ArgumentException.ThrowIfNullOrEmpty(code3);
		Int32 idAsInteger = 1;
		Byte[] id3Bytes = Encoding.ASCII.GetBytes(code3.ToLowerInvariant());
		idAsInteger |= ((id3Bytes[0] - (Byte)'a') & 0b11111) << 1;
		idAsInteger |= ((id3Bytes[1] - (Byte)'a') & 0b11111) << 6;
		idAsInteger |= ((id3Bytes[2] - (Byte)'a') & 0b11111) << 11;

		if (!String.IsNullOrWhiteSpace(code2)) {
			Byte[] id2Bytes = Encoding.ASCII.GetBytes(code2.ToLowerInvariant());

			idAsInteger |= 1 << 16;
			idAsInteger |= ((id2Bytes[0] - (Byte)'a') & 0b11111) << 17;
			idAsInteger |= ((id2Bytes[1] - (Byte)'a') & 0b11111) << 22;
		}


		return idAsInteger.ToString("N0", new NumberFormatInfo() { NumberGroupSeparator = "_" });
	}

	public static String RemoveDiacritics(String text) {
		String normalizedString = text.Normalize(NormalizationForm.FormD);
		StringBuilder stringBuilder = new StringBuilder();

		foreach (Rune c in normalizedString.EnumerateRunes()) {
			UnicodeCategory unicodeCategory = Rune.GetUnicodeCategory(c);
			if (unicodeCategory != UnicodeCategory.NonSpacingMark) {
				stringBuilder.Append(c);
			}
		}

		return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
	}
	
	internal static HashSet<GenericEnumMember> GetCurrentlyAvailableEnumMembers<TEnum>() where TEnum : struct, Enum {
		XmlDocument isoEnumsDocumentation = new();
		isoEnumsDocumentation.PreserveWhitespace = true;
		XmlReaderSettings readerSettings = new() {
			IgnoreWhitespace = false,
		};
		using FileStream fileStream = File.OpenRead("IsoEnums.xml");
		using XmlReader reader = XmlReader.Create(fileStream, readerSettings);
		isoEnumsDocumentation.Load(reader);

		HashSet<GenericEnumMember> knownCurrencies = [];
		String nodeNamePrefix = $"F:{typeof(TEnum).GetFullName()}.";
		foreach (XmlElement node in isoEnumsDocumentation.SelectNodes($"/doc/members/member[starts-with(@name,'{nodeNamePrefix}')]")!) {
			String documentation = String.Join(Environment.NewLine, node.InnerXml.Trim().Split(['\r','\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(line => $"/// {line}"));
			String nodeName = node.GetAttribute("name").Substring(nodeNamePrefix.Length);
			TEnum enumValue = Enum.Parse<TEnum>(nodeName);
			knownCurrencies.Add(new GenericEnumMember(nodeName, ((Int32)(ValueType)enumValue).ToString(BaseGenerator.NumberFormatForEnums), documentation));
		}

		return knownCurrencies;
	}

	
}