namespace IsoEnums.Generator;

using System.Globalization;
using System.Text;

internal static class BaseGenerator {
	public static void AppendDefaultHeader(StringBuilder sb) {
		sb.AppendLine("// <auto-generated>");
		sb.AppendLine("//   This file was generated by a tool; you should avoid making direct changes.");
		sb.AppendLine("// </auto-generated>");
		sb.AppendLine(CultureInfo.InvariantCulture, $"// Generated on {DateTime.UtcNow:F} UTC");
		sb.AppendLine();
	}

	public static String RemoveDiacritics(String text) {
		String normalizedString = text.Normalize(NormalizationForm.FormD);
		StringBuilder stringBuilder = new StringBuilder();

		foreach (Rune c in normalizedString.EnumerateRunes()) {
			UnicodeCategory unicodeCategory = Rune.GetUnicodeCategory(c);
			if (unicodeCategory != UnicodeCategory.NonSpacingMark) {
				stringBuilder.Append(c);
			}
		}

		return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
	}

	public static IFormatProvider NumberFormatForEnums { get; } = new NumberFormatInfo { NumberGroupSeparator = "_" };
}