// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
// </auto-generated>
// Generated on Monday, 09 February 2026 18:27:16 UTC

namespace IsoEnums.Iso4217;
#region Designer generated code
/// <summary>ISO 4217 is a standard that defines alpha and numeric codes for the representation of currencies</summary>
public enum Currency {
/// <summary>Not a currency.</summary>
NotACurrency=-1,
/// <summary>Not a currency, but instead an uninitialized variable.</summary>
Uninitialized=0,
/// <summary>
/// <para>Afghani</para>
/// </summary>
/// <value>id=AFN, numeric=971</value>
Afghani=1_765_802_955,
/// <summary>
/// <para>Algerian Dinar</para>
/// </summary>
/// <value>id=DZD, numeric=12</value>
AlgerianDinar=507_904_012,
/// <summary>
/// <para>Arab Accounting Dinar</para>
/// </summary>
/// <value>id=XAD, numeric=396</value>
ArabAccountingDinar=405_668_236,
/// <summary>
/// <para>Argentine Peso</para>
/// </summary>
/// <value>id=ARS, numeric=32</value>
ArgentinePeso=-1_807_744_992,
/// <summary>
/// <para>Armenian Dram</para>
/// </summary>
/// <value>id=AMD, numeric=51</value>
ArmenianDram=452_984_883,
/// <summary>
/// <para>Aruban Florin</para>
/// </summary>
/// <value>id=AWG, numeric=533</value>
ArubanFlorin=897_581_589,
/// <summary>
/// <para>Australian Dollar</para>
/// </summary>
/// <value>id=AUD, numeric=36</value>
AustralianDollar=486_539_300,
/// <summary>
/// <para>Azerbaijan Manat</para>
/// </summary>
/// <value>id=AZN, numeric=944</value>
AzerbaijanManat=1_849_689_008,
/// <summary>
/// <para>Bahamian Dollar</para>
/// </summary>
/// <value>id=BSD, numeric=44</value>
BahamianDollar=478_281_772,
/// <summary>
/// <para>Bahraini Dinar</para>
/// </summary>
/// <value>id=BHD, numeric=48</value>
BahrainiDinar=432_144_432,
/// <summary>
/// <para>Baht</para>
/// </summary>
/// <value>id=THB, numeric=764</value>
Baht=166_068_988,
/// <summary>
/// <para>Balboa</para>
/// </summary>
/// <value>id=PAB, numeric=590</value>
Balboa=136_184_398,
/// <summary>
/// <para>Barbados Dollar</para>
/// </summary>
/// <value>id=BBD, numeric=52</value>
BarbadosDollar=406_978_612,
/// <summary>
/// <para>Belarusian Ruble</para>
/// </summary>
/// <value>id=BYN, numeric=933</value>
BelarusianRuble=1_845_625_765,
/// <summary>
/// <para>Belize Dollar</para>
/// </summary>
/// <value>id=BZD, numeric=84</value>
BelizeDollar=507_641_940,
/// <summary>
/// <para>Bermudian Dollar</para>
/// </summary>
/// <value>id=BMD, numeric=60</value>
BermudianDollar=453_115_964,
/// <summary>
/// <para>Bolívar Soberano</para>
/// </summary>
/// <value>id=VED, numeric=926</value>
BolivarSoberano_VED=422_183_838,
/// <summary>
/// <para>Bolívar Soberano</para>
/// </summary>
/// <value>id=VES, numeric=928</value>
BolivarSoberano_VES=-1_859_517_536,
/// <summary>
/// <para>Boliviano</para>
/// </summary>
/// <value>id=BOB, numeric=68</value>
Boliviano=193_069_124,
/// <summary>
/// <para>Brazilian Real</para>
/// </summary>
/// <value>id=BRL, numeric=986</value>
BrazilianReal=1_547_830_234,
/// <summary>
/// <para>Brunei Dollar</para>
/// </summary>
/// <value>id=BND, numeric=96</value>
BruneiDollar=457_310_304,
/// <summary>
/// <para>Bulgarian Lev</para>
/// </summary>
/// <value>id=BGN, numeric=975</value>
[Obsolete("Replaced by Euro starting 2026-01-01")]
BulgarianLev=63924611,
/// <summary>
/// <para>Burundi Franc</para>
/// </summary>
/// <value>id=BIF, numeric=108</value>
BurundiFranc=704_774_252,
/// <summary>
/// <para>Cabo Verde Escudo</para>
/// </summary>
/// <value>id=CVE, numeric=132</value>
CaboVerdeEscudo=625_213_572,
/// <summary>
/// <para>Canadian Dollar</para>
/// </summary>
/// <value>id=CAD, numeric=124</value>
CanadianDollar=402_915_452,
/// <summary>
/// <para>Caribbean Guilder</para>
/// </summary>
/// <value>id=XCG, numeric=532</value>
CaribbeanGuilder=816_710_164,
/// <summary>
/// <para>Cayman Islands Dollar</para>
/// </summary>
/// <value>id=KYD, numeric=136</value>
CaymanIslandsDollar=504_627_336,
/// <summary>
/// <para>CFA Franc BCEAO</para>
/// </summary>
/// <value>id=XOF, numeric=952</value>
CFAFrancBCEAO=732_824_504,
/// <summary>
/// <para>CFA Franc BEAC</para>
/// </summary>
/// <value>id=XAF, numeric=950</value>
CFAFrancBEAC=674_104_246,
/// <summary>
/// <para>CFP Franc</para>
/// </summary>
/// <value>id=XPF, numeric=953</value>
CFPFranc=737_018_809,
/// <summary>
/// <para>Chilean Peso</para>
/// </summary>
/// <value>id=CLP, numeric=152</value>
ChileanPeso=2_059_665_560,
/// <summary>
/// <para>Colombian Peso</para>
/// </summary>
/// <value>id=COP, numeric=170</value>
ColombianPeso=2_072_248_490,
/// <summary>
/// <para>Comorian Franc </para>
/// </summary>
/// <value>id=KMF, numeric=174</value>
ComorianFranc=722_731_182,
/// <summary>
/// <para>Congolese Franc</para>
/// </summary>
/// <value>id=CDF, numeric=976</value>
CongoleseFranc=683_934_672,
/// <summary>
/// <para>Convertible Mark</para>
/// </summary>
/// <value>id=BAM, numeric=977</value>
ConvertibleMark=1_610_744_785,
/// <summary>
/// <para>Cordoba Oro</para>
/// </summary>
/// <value>id=NIO, numeric=558</value>
CordobaOro=1_914_307_118,
/// <summary>
/// <para>Costa Rican Colon</para>
/// </summary>
/// <value>id=CRC, numeric=188</value>
CostaRicanColon=340_000_956,
/// <summary>
/// <para>Cuban Peso</para>
/// </summary>
/// <value>id=CUP, numeric=192</value>
CubanPeso=2_097_414_336,
/// <summary>
/// <para>Czech Koruna</para>
/// </summary>
/// <value>id=CZK, numeric=203</value>
CzechKoruna=1_447_297_227,
/// <summary>
/// <para>Dalasi</para>
/// </summary>
/// <value>id=GMD, numeric=270</value>
Dalasi=453_771_534,
/// <summary>
/// <para>Danish Krone</para>
/// </summary>
/// <value>id=DKK, numeric=208</value>
DanishKrone=1_384_513_744,
/// <summary>
/// <para>Denar</para>
/// </summary>
/// <value>id=MKD, numeric=807</value>
Denar=446_169_895,
/// <summary>
/// <para>Djibouti Franc</para>
/// </summary>
/// <value>id=DJF, numeric=262</value>
DjiboutiFranc=709_230_854,
/// <summary>
/// <para>Dobra</para>
/// </summary>
/// <value>id=STN, numeric=930</value>
Dobra=1_826_882_466,
/// <summary>
/// <para>Dominican Peso</para>
/// </summary>
/// <value>id=DOP, numeric=214</value>
DominicanPeso=2_072_379_606,
/// <summary>
/// <para>Dong</para>
/// </summary>
/// <value>id=VND, numeric=704</value>
Dong=459_932_352,
/// <summary>
/// <para>East Caribbean Dollar</para>
/// </summary>
/// <value>id=XCD, numeric=951</value>
EastCaribbeanDollar=414_057_399,
/// <summary>
/// <para>Egyptian Pound</para>
/// </summary>
/// <value>id=EGP, numeric=818</value>
EgyptianPound=2_038_956_850,
/// <summary>
/// <para>El Salvador Colon</para>
/// </summary>
/// <value>id=SVC, numeric=222</value>
ElSalvadorColon=358_875_358,
/// <summary>
/// <para>Ethiopian Birr</para>
/// </summary>
/// <value>id=ETB, numeric=230</value>
EthiopianBirr=214_434_022,
/// <summary>
/// <para>Euro</para>
/// </summary>
/// <value>id=EUR, numeric=978</value>
Euro=-1_928_854_574,
/// <summary>
/// <para>Falkland Islands Pound</para>
/// </summary>
/// <value>id=FKP, numeric=238</value>
FalklandIslandsPound=2_055_864_558,
/// <summary>
/// <para>Fiji Dollar</para>
/// </summary>
/// <value>id=FJD, numeric=242</value>
FijiDollar=441_057_522,
/// <summary>
/// <para>Forint</para>
/// </summary>
/// <value>id=HUF, numeric=348</value>
Forint=755_892_572,
/// <summary>
/// <para>Ghana Cedi</para>
/// </summary>
/// <value>id=GHS, numeric=936</value>
GhanaCedi=-1_848_900_696,
/// <summary>
/// <para>Gibraltar Pound</para>
/// </summary>
/// <value>id=GIP, numeric=292</value>
GibraltarPound=2_047_607_076,
/// <summary>
/// <para>Gold</para>
/// </summary>
/// <value>id=XAU, numeric=959</value>
Gold=-1_607_597_121,
/// <summary>
/// <para>Gourde</para>
/// </summary>
/// <value>id=HTG, numeric=332</value>
Gourde=885_915_980,
/// <summary>
/// <para>Guarani</para>
/// </summary>
/// <value>id=PYG, numeric=600</value>
Guarani=907_936_344,
/// <summary>
/// <para>Guinean Franc</para>
/// </summary>
/// <value>id=GNF, numeric=324</value>
GuineanFranc=726_401_348,
/// <summary>
/// <para>Guyana Dollar</para>
/// </summary>
/// <value>id=GYD, numeric=328</value>
GuyanaDollar=504_103_240,
/// <summary>
/// <para>Hong Kong Dollar</para>
/// </summary>
/// <value>id=HKD, numeric=344</value>
HongKongDollar=445_514_072,
/// <summary>
/// <para>Hryvnia</para>
/// </summary>
/// <value>id=UAH, numeric=980</value>
Hryvnia=942_146_516,
/// <summary>
/// <para>Iceland Krona</para>
/// </summary>
/// <value>id=ISK, numeric=352</value>
IcelandKrona=1_418_723_680,
/// <summary>
/// <para>Indian Rupee</para>
/// </summary>
/// <value>id=INR, numeric=356</value>
IndianRupee=-1_957_691_036,
/// <summary>
/// <para>Iranian Rial</para>
/// </summary>
/// <value>id=IRR, numeric=364</value>
IranianRial=-1_940_913_812,
/// <summary>
/// <para>Iraqi Dinar</para>
/// </summary>
/// <value>id=IQD, numeric=368</value>
IraqiDinar=470_810_992,
/// <summary>
/// <para>Jamaican Dollar</para>
/// </summary>
/// <value>id=JMD, numeric=388</value>
JamaicanDollar=454_164_868,
/// <summary>
/// <para>Jordanian Dinar</para>
/// </summary>
/// <value>id=JOD, numeric=400</value>
JordanianDinar=462_553_488,
/// <summary>
/// <para>Kenyan Shilling</para>
/// </summary>
/// <value>id=KES, numeric=404</value>
KenyanShilling=-1_860_959_852,
/// <summary>
/// <para>Kina</para>
/// </summary>
/// <value>id=PGK, numeric=598</value>
Kina=1_369_309_782,
/// <summary>
/// <para>Kuwaiti Dinar</para>
/// </summary>
/// <value>id=KWD, numeric=414</value>
KuwaitiDinar=496_239_006,
/// <summary>
/// <para>Kwanza</para>
/// </summary>
/// <value>id=AOA, numeric=973</value>
Kwanza=58_721_229,
/// <summary>
/// <para>Kyat</para>
/// </summary>
/// <value>id=MMK, numeric=104</value>
Kyat=1_394_081_896,
/// <summary>
/// <para>Lao Kip</para>
/// </summary>
/// <value>id=LAK, numeric=418</value>
LaoKip=1_343_619_490,
/// <summary>
/// <para>Lari</para>
/// </summary>
/// <value>id=GEL, numeric=981</value>
Lari=1_493_959_637,
/// <summary>
/// <para>Lebanese Pound</para>
/// </summary>
/// <value>id=LBP, numeric=422</value>
LebanesePound=2_018_902_438,
/// <summary>
/// <para>Lek</para>
/// </summary>
/// <value>id=ALL, numeric=8</value>
Lek=1_522_532_360,
/// <summary>
/// <para>Lempira</para>
/// </summary>
/// <value>id=HNL, numeric=340</value>
Lempira=1_531_838_804,
/// <summary>
/// <para>Leone</para>
/// </summary>
/// <value>id=SLE, numeric=925</value>
Leone=585_368_477,
/// <summary>
/// <para>Liberian Dollar</para>
/// </summary>
/// <value>id=LRD, numeric=430</value>
LiberianDollar=475_398_574,
/// <summary>
/// <para>Libyan Dinar</para>
/// </summary>
/// <value>id=LYD, numeric=434</value>
LibyanDinar=504_758_706,
/// <summary>
/// <para>Lilangeni</para>
/// </summary>
/// <value>id=SZL, numeric=748</value>
Lilangeni=1_583_612_652,
/// <summary>
/// <para>Loti</para>
/// </summary>
/// <value>id=LSL, numeric=426</value>
Loti=1_553_334_698,
/// <summary>
/// <para>Malagasy Ariary</para>
/// </summary>
/// <value>id=MGA, numeric=969</value>
MalagasyAriary=26_739_657,
/// <summary>
/// <para>Malawi Kwacha</para>
/// </summary>
/// <value>id=MWK, numeric=454</value>
MalawiKwacha=1_436_025_286,
/// <summary>
/// <para>Malaysian Ringgit</para>
/// </summary>
/// <value>id=MYR, numeric=458</value>
MalaysianRinggit=-1_911_029_302,
/// <summary>
/// <para>Mauritius Rupee</para>
/// </summary>
/// <value>id=MUR, numeric=480</value>
MauritiusRupee=-1_927_806_496,
/// <summary>
/// <para>Mexican Peso</para>
/// </summary>
/// <value>id=MXN, numeric=484</value>
MexicanPeso=1_842_872_804,
/// <summary>
/// <para>Mexican Unidad de Inversion (UDI)</para>
/// </summary>
/// <value>id=MXV, numeric=979</value>
MexicanUnidaddeInversion=-1_378_352_173,
/// <summary>
/// <para>Moldovan Leu</para>
/// </summary>
/// <value>id=MDL, numeric=498</value>
MoldovanLeu=1_490_551_282,
/// <summary>
/// <para>Moroccan Dirham</para>
/// </summary>
/// <value>id=MAD, numeric=504</value>
MoroccanDirham=404_226_552,
/// <summary>
/// <para>Mozambique Metical</para>
/// </summary>
/// <value>id=MZN, numeric=943</value>
MozambiqueMetical=1_851_261_871,
/// <summary>
/// <para>Mvdol</para>
/// </summary>
/// <value>id=BOV, numeric=984</value>
Mvdol=-1_417_542_696,
/// <summary>
/// <para>Naira</para>
/// </summary>
/// <value>id=NGN, numeric=566</value>
Naira=1_771_700_790,
/// <summary>
/// <para>Nakfa</para>
/// </summary>
/// <value>id=ERN, numeric=232</value>
Nakfa=1_816_658_152,
/// <summary>
/// <para>Namibia Dollar</para>
/// </summary>
/// <value>id=NAD, numeric=516</value>
NamibiaDollar=404_357_636,
/// <summary>
/// <para>Nepalese Rupee</para>
/// </summary>
/// <value>id=NPR, numeric=524</value>
NepaleseRupee=-1_948_646_900,
/// <summary>
/// <para>New Israeli Sheqel</para>
/// </summary>
/// <value>id=ILS, numeric=376</value>
NewIsraeliSheqel=-1_831_861_896,
/// <summary>
/// <para>New Taiwan Dollar</para>
/// </summary>
/// <value>id=TWD, numeric=901</value>
NewTaiwanDollar=497_419_141,
/// <summary>
/// <para>New Zealand Dollar</para>
/// </summary>
/// <value>id=NZD, numeric=554</value>
NewZealandDollar=509_215_274,
/// <summary>
/// <para>Ngultrum</para>
/// </summary>
/// <value>id=BTN, numeric=64</value>
Ngultrum=1_824_653_376,
/// <summary>
/// <para>The codes assigned for transactions where no currency is involved</para>
/// </summary>
/// <value>id=XXX, numeric=999</value>
NoCurrencyInvolved=-1_108_474_905,
/// <summary>
/// <para>North Korean Won</para>
/// </summary>
/// <value>id=KPW, numeric=408</value>
NorthKoreanWon=-1_277_951_592,
/// <summary>
/// <para>Norwegian Krone</para>
/// </summary>
/// <value>id=NOK, numeric=578</value>
NorwegianKrone=1_402_602_050,
/// <summary>
/// <para>Ouguiya</para>
/// </summary>
/// <value>id=MRU, numeric=929</value>
Ouguiya=-1_537_735_775,
/// <summary>
/// <para>Pa’anga</para>
/// </summary>
/// <value>id=TOP, numeric=776</value>
Paanga=2_074_477_320,
/// <summary>
/// <para>Pakistan Rupee</para>
/// </summary>
/// <value>id=PKR, numeric=586</value>
PakistanRupee=-1_969_356_214,
/// <summary>
/// <para>Palladium</para>
/// </summary>
/// <value>id=XPD, numeric=964</value>
Palladium=468_583_364,
/// <summary>
/// <para>Pataca</para>
/// </summary>
/// <value>id=MOP, numeric=446</value>
Pataca=2_073_559_486,
/// <summary>
/// <para>Peso Uruguayo</para>
/// </summary>
/// <value>id=UYU, numeric=858</value>
PesoUruguayo=-1_507_327_142,
/// <summary>
/// <para>Philippine Peso</para>
/// </summary>
/// <value>id=PHP, numeric=608</value>
PhilippinePeso=2_044_592_736,
/// <summary>
/// <para>Platinum</para>
/// </summary>
/// <value>id=XPT, numeric=962</value>
Platinum=-1_678_900_286,
/// <summary>
/// <para>Pound Sterling</para>
/// </summary>
/// <value>id=GBP, numeric=826</value>
PoundSterling=2_018_247_482,
/// <summary>
/// <para>Pula</para>
/// </summary>
/// <value>id=BWP, numeric=72</value>
Pula=2_105_671_752,
/// <summary>
/// <para>Qatari Rial</para>
/// </summary>
/// <value>id=QAR, numeric=634</value>
QatariRial=-2_011_168_134,
/// <summary>
/// <para>Quetzal</para>
/// </summary>
/// <value>id=GTQ, numeric=320</value>
Quetzal=-2_067_005_120,
/// <summary>
/// <para>Rand</para>
/// </summary>
/// <value>id=ZAR, numeric=710</value>
Rand=-2_009_988_410,
/// <summary>
/// <para>Rial Omani</para>
/// </summary>
/// <value>id=OMR, numeric=512</value>
RialOmani=-1_961_098_752,
/// <summary>
/// <para>Riel</para>
/// </summary>
/// <value>id=KHR, numeric=116</value>
Riel=-1_982_594_956,
/// <summary>
/// <para>Romanian Leu</para>
/// </summary>
/// <value>id=RON, numeric=946</value>
RomanianLeu=1_805_779_890,
/// <summary>
/// <para>Rufiyaa</para>
/// </summary>
/// <value>id=MVR, numeric=462</value>
Rufiyaa=-1_923_612_210,
/// <summary>
/// <para>Rupiah</para>
/// </summary>
/// <value>id=IDR, numeric=360</value>
Rupiah=-1_999_634_072,
/// <summary>
/// <para>Russian Ruble</para>
/// </summary>
/// <value>id=RUB, numeric=643</value>
RussianRuble=220_332_675,
/// <summary>
/// <para>Rwanda Franc</para>
/// </summary>
/// <value>id=RWF, numeric=646</value>
RwandaFranc=765_592_198,
/// <summary>
/// <para>Saint Helena Pound</para>
/// </summary>
/// <value>id=SHP, numeric=654</value>
SaintHelenaPound=2_044_985_998,
/// <summary>
/// <para>Saudi Riyal</para>
/// </summary>
/// <value>id=SAR, numeric=682</value>
SaudiRiyal=-2_010_905_942,
/// <summary>
/// <para>Serbian Dinar</para>
/// </summary>
/// <value>id=RSD, numeric=941</value>
SerbianDinar=480_379_821,
/// <summary>
/// <para>Seychelles Rupee</para>
/// </summary>
/// <value>id=SCR, numeric=690</value>
SeychellesRupee=-2_002_517_326,
/// <summary>
/// <para>Silver</para>
/// </summary>
/// <value>id=XAG, numeric=961</value>
Silver=808_321_985,
/// <summary>
/// <para>Singapore Dollar</para>
/// </summary>
/// <value>id=SGD, numeric=702</value>
SingaporeDollar=430_179_006,
/// <summary>
/// <para>Sol</para>
/// </summary>
/// <value>id=PEN, numeric=604</value>
Sol=1_763_574_364,
/// <summary>
/// <para>Solomon Islands Dollar</para>
/// </summary>
/// <value>id=SBD, numeric=90</value>
SolomonIslandsDollar=409_206_874,
/// <summary>
/// <para>Som</para>
/// </summary>
/// <value>id=KGS, numeric=417</value>
Som=-1_852_571_231,
/// <summary>
/// <para>Somali Shilling</para>
/// </summary>
/// <value>id=SOS, numeric=706</value>
SomaliShilling=-1_817_967_934,
/// <summary>
/// <para>Somoni</para>
/// </summary>
/// <value>id=TJS, numeric=972</value>
Somoni=-1_838_808_116,
/// <summary>
/// <para>South Sudanese Pound</para>
/// </summary>
/// <value>id=SSP, numeric=728</value>
SouthSudanesePound=2_091_123_416,
/// <summary>
/// <para>Sri Lanka Rupee</para>
/// </summary>
/// <value>id=LKR, numeric=144</value>
SriLankaRupee=-1_969_880_944,
/// <summary>
/// <para>Sucre</para>
/// </summary>
/// <value>id=XSU, numeric=994</value>
Sucre=-1_532_099_614,
/// <summary>
/// <para>Sudanese Pound</para>
/// </summary>
/// <value>id=SDG, numeric=938</value>
SudanesePound=820_249_514,
/// <summary>
/// <para>Surinam Dollar</para>
/// </summary>
/// <value>id=SRD, numeric=968</value>
SurinamDollar=476_316_616,
/// <summary>
/// <para>Swedish Krona</para>
/// </summary>
/// <value>id=SEK, numeric=752</value>
SwedishKrona=1_361_314_544,
/// <summary>
/// <para>Swiss Franc</para>
/// </summary>
/// <value>id=CHF, numeric=756</value>
SwissFranc=700_711_668,
/// <summary>
/// <para>Syrian Pound</para>
/// </summary>
/// <value>id=SYP, numeric=760</value>
SyrianPound=2_116_289_272,
/// <summary>
/// <para>Taka</para>
/// </summary>
/// <value>id=BDT, numeric=50</value>
Taka=-1_732_116_430,
/// <summary>
/// <para>Tala</para>
/// </summary>
/// <value>id=WST, numeric=882</value>
Tala=-1_666_448_526,
/// <summary>
/// <para>Tanzanian Shilling</para>
/// </summary>
/// <value>id=TZS, numeric=834</value>
TanzanianShilling=-1_771_699_390,
/// <summary>
/// <para>Tenge</para>
/// </summary>
/// <value>id=KZT, numeric=398</value>
Tenge=-1_638_661_746,
/// <summary>
/// <para>Codes specifically reserved for testing purposes</para>
/// </summary>
/// <value>id=XTS, numeric=963</value>
TestCurrency=-1_796_340_797,
/// <summary>
/// <para>Trinidad and Tobago Dollar</para>
/// </summary>
/// <value>id=TTD, numeric=780</value>
TrinidadandTobagoDollar=484_836_108,
/// <summary>
/// <para>Tugrik</para>
/// </summary>
/// <value>id=MNT, numeric=496</value>
Tugrik=-1_688_731_152,
/// <summary>
/// <para>Tunisian Dinar</para>
/// </summary>
/// <value>id=TND, numeric=788</value>
TunisianDinar=459_670_292,
/// <summary>
/// <para>Turkish Lira</para>
/// </summary>
/// <value>id=TRY, numeric=949</value>
TurkishLira=-999_947_339,
/// <summary>
/// <para>Turkmenistan New Manat</para>
/// </summary>
/// <value>id=TMT, numeric=934</value>
TurkmenistanNewManat=-1_692_007_514,
/// <summary>
/// <para>UAE Dirham</para>
/// </summary>
/// <value>id=AED, numeric=784</value>
UAEDirham=419_431_184,
/// <summary>
/// <para>Uganda Shilling</para>
/// </summary>
/// <value>id=UGX, numeric=800</value>
UgandaShilling=-1_180_171_488,
/// <summary>
/// <para>Unidad de Fomento</para>
/// </summary>
/// <value>id=CLF, numeric=990</value>
UnidaddeFomento=717_489_118,
/// <summary>
/// <para>Unidad de Valor Real</para>
/// </summary>
/// <value>id=COU, numeric=970</value>
UnidaddeValorReal=-1_551_629_366,
/// <summary>
/// <para>Unidad Previsional</para>
/// </summary>
/// <value>id=UYW, numeric=927</value>
UnidadPrevisional=-1_238_891_617,
/// <summary>
/// <para>Uruguay Peso en Unidades Indexadas (UI)</para>
/// </summary>
/// <value>id=UYI, numeric=940</value>
UruguayPesoenUnidadesIndexadas=1_177_027_500,
/// <summary>
/// <para>US Dollar</para>
/// </summary>
/// <value>id=USD, numeric=840</value>
USDollar=480_772_936,
/// <summary>
/// <para>Uzbekistan Sum</para>
/// </summary>
/// <value>id=UZS, numeric=860</value>
UzbekistanSum=-1_771_568_292,
/// <summary>
/// <para>Vatu</para>
/// </summary>
/// <value>id=VUV, numeric=548</value>
Vatu=-1_389_755_868,
/// <summary>
/// <para>WIR Euro</para>
/// </summary>
/// <value>id=CHE, numeric=947</value>
WIREuro=566_494_131,
/// <summary>
/// <para>WIR Franc</para>
/// </summary>
/// <value>id=CHW, numeric=948</value>
WIRFranc=-1_312_554_060,
/// <summary>
/// <para>Won</para>
/// </summary>
/// <value>id=KRW, numeric=410</value>
Won=-1_269_562_982,
/// <summary>
/// <para>Yemeni Rial</para>
/// </summary>
/// <value>id=YER, numeric=886</value>
YemeniRial=-1_993_342_090,
/// <summary>
/// <para>Yen</para>
/// </summary>
/// <value>id=JPY, numeric=392</value>
Yen=-1_009_647_224,
/// <summary>
/// <para>Yuan Renminbi</para>
/// </summary>
/// <value>id=CNY, numeric=156</value>
YuanRenminbi=-1_018_953_572,
/// <summary>
/// <para>Zambian Kwacha</para>
/// </summary>
/// <value>id=ZMW, numeric=967</value>
ZambianKwacha=-1_288_567_865,
/// <summary>
/// <para>Zimbabwe Gold</para>
/// </summary>
/// <value>id=ZWG, numeric=924</value>
ZimbabweGold=900_858_780,
/// <summary>
/// <para>Zloty</para>
/// </summary>
/// <value>id=PLN, numeric=985</value>
Zloty=1_792_934_873,
}
#endregion